// <auto-generated />
using System;
using DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(DataDBContext))]
    partial class DataDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccessLayer.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6382203e-e51f-4982-a551-38fc7ca492a6"),
                            CreatedTime = new DateTime(2023, 7, 6, 14, 49, 54, 925, DateTimeKind.Local).AddTicks(4020),
                            IsSuccess = true,
                            Name = "Mutfak Tasarımı "
                        },
                        new
                        {
                            Id = new Guid("a0e8e78e-342c-43db-8542-499118ee87c0"),
                            CreatedTime = new DateTime(2023, 7, 6, 14, 49, 54, 925, DateTimeKind.Local).AddTicks(4051),
                            IsSuccess = true,
                            Name = "Yemek Odası Tasarımı"
                        },
                        new
                        {
                            Id = new Guid("0a41149e-8ad9-4f18-85c5-cbd43afb8ef4"),
                            CreatedTime = new DateTime(2023, 7, 6, 14, 49, 54, 925, DateTimeKind.Local).AddTicks(4056),
                            IsSuccess = true,
                            Name = "Yemek Masası Tasarımı"
                        },
                        new
                        {
                            Id = new Guid("ea437201-61f6-4bde-ad28-d2bf5f0ced94"),
                            CreatedTime = new DateTime(2023, 7, 6, 14, 49, 54, 925, DateTimeKind.Local).AddTicks(4060),
                            IsSuccess = true,
                            Name = "Banyo Tasarımı"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Register", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Registers");
                });
#pragma warning restore 612, 618
        }
    }
}
